<a href="https://colab.research.google.com/github/Drishti05/Python-for-Data-Science-Machine-Learning-from-A-Z/blob/main/NumPy_Data_Analysis/Numpy_Arrays_Basics/Numpy_Arrays_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Arrays Basic

In [11]:
import numpy as np

In [12]:
arr=np.random.randint(10,size=(3,4,5))

In [13]:
print("arr ndim:",arr.ndim)

arr ndim: 3


In [14]:
print("arr shape:",arr.shape)

arr shape: (3, 4, 5)


In [15]:
print("arr size:",arr.size)

arr size: 60


## 3D Array

In [16]:
arr1=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [17]:
print(arr1.ndim)

3


In [18]:
print(arr1.shape)

(2, 2, 2)


In [19]:
arr2= np.ones((4,3,2))

In [20]:
print(arr2)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [21]:
arr3=np.zeros((4,3,2))

In [22]:
print(arr3)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [23]:
arr4=np.random.random((4,3,2))

In [24]:
print(arr4)

[[[0.46139139 0.93681985]
  [0.8598101  0.91835785]
  [0.04560867 0.06518212]]

 [[0.25795894 0.59550996]
  [0.97497395 0.92626111]
  [0.34846917 0.60498372]]

 [[0.50598834 0.63949995]
  [0.48372841 0.17421825]
  [0.46587909 0.93955596]]

 [[0.48762551 0.45478755]
  [0.18519645 0.50936789]
  [0.53300891 0.76848435]]]


## Array Indexing

In [26]:
array=np.array([5,0,3,3,7,9])

In [27]:
array

array([5, 0, 3, 3, 7, 9])

In [28]:
array[0]

5

In [29]:
array[4]

7

In [30]:
array[-1]

9

In [31]:
array[-2]

7

In [32]:
array1=np.array([[3,5,2,4],[7,6,8,8],[1,6,7,7]])

In [33]:
array1

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [34]:
array1[0,0]

3

In [35]:
array1[2,0]

1

In [36]:
array1[2,-1]

7