<a href="https://colab.research.google.com/github/Drishti05/Python-for-Data-Science-Machine-Learning-from-A-Z/blob/main/NumPy_Data_Analysis/NumPy_Array_Indexing/Numpy_Array_Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Array Slicing

In [2]:
import numpy as np

In [4]:
array= np.arange(10)

In [5]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 1 D Slicing

## First five elements

In [6]:
array[:5]

array([0, 1, 2, 3, 4])

## Elements after index 5

In [7]:
array[5:]

array([5, 6, 7, 8, 9])

## Middle Subarray

In [8]:
array[4:7]

array([4, 5, 6])

## Every other element

In [9]:
array[::2]

array([0, 2, 4, 6, 8])

## Every other element starting at index 1

In [10]:
array[1::2]

array([1, 3, 5, 7, 9])

# 2 D Slicing

In [11]:
arrays2 =np.array([[12,5,2,4],[7,6,8,8],[1,6,7,7]])

In [12]:
arrays2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

## two rows three columns

In [13]:
arrays2[:2,:3]

array([[12,  5,  2],
       [ 7,  6,  8]])

# all rows, every other column 

In [14]:
arrays2[:3,::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

# Reshaping Arrays

In [16]:
grid=np.arange(1,10).reshape((3,3))

In [17]:
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
grid=np.arange(1,7).reshape((2,3))

In [19]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
grid=np.arange(1,7).reshape((3,2))

In [21]:
grid

array([[1, 2],
       [3, 4],
       [5, 6]])