<a href="https://colab.research.google.com/github/Drishti05/Python-for-Data-Science-Machine-Learning-from-A-Z/blob/main/NumPy_Data_Analysis/Broadcasting/Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Computation on Arrays

In [1]:
import numpy as np

In [2]:
a= np.array([0,1,2])

In [3]:
b= np.array([5,5,5])

In [4]:
a+b

array([5, 6, 7])

In [7]:
arr1= np.arange(3)

In [8]:
arr1

array([0, 1, 2])

In [9]:
arr1+5

array([5, 6, 7])

In [10]:
arr2= np.ones((3,3))

In [11]:
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
arr2+ np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [20]:
arr3= np.array([[0],[1],[2]])

In [21]:
arr3

array([[0],
       [1],
       [2]])

In [22]:
arr3+ np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## Comparison Functions

In [23]:
array= np.array([1,2,3,4,5])

In [24]:
array

array([1, 2, 3, 4, 5])

## less than

In [25]:
array<3

array([ True,  True, False, False, False])

## greater than

In [26]:
array>3

array([False, False, False,  True,  True])

## less than or equal

In [28]:
array<=3

array([ True,  True,  True, False, False])

## greater than or equal

In [29]:
array>=3

array([False, False,  True,  True,  True])

## not equal

In [30]:
array !=3

array([ True,  True, False,  True,  True])

## equal

In [31]:
array==3

array([False, False,  True, False, False])