<a href="https://colab.research.google.com/github/Drishti05/Python-for-Data-Science-Machine-Learning-from-A-Z/blob/main/NumPy_Data_Analysis/NumPy_Array_Computations/Numpy_Array_Computations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Arithmetic Ufuncs

In [1]:
import numpy as  np

In [2]:
array=np.arange(4)

In [3]:
array

array([0, 1, 2, 3])

In [4]:
print("array+5 =", array+5)

array+5 = [5 6 7 8]


In [5]:
print("array-5 =", array-5)

array-5 = [-5 -4 -3 -2]


In [9]:
print("array*2 =", array*2)

array*2 = [0 2 4 6]


In [10]:
print("array/5 =", array/5)

array/5 = [0.  0.2 0.4 0.6]


## Numpy Aggregation function

In [11]:
array1= np.array([[1,2],[3,4],[5,6]])

In [12]:
array1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
array1.max()

6

In [14]:
array1.min()

1

In [15]:
array1.sum()

21

In [16]:
array1.max(axis=0)

array([5, 6])

In [17]:
array1.max(axis=1)

array([2, 4, 6])