<a href="https://colab.research.google.com/github/Drishti05/Python-for-Data-Science-Machine-Learning-from-A-Z/blob/main/NumPy_Data_Analysis/Numpy_Arrays/Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Arrays

In [2]:
import numpy as np

In [3]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

## Fixed data type

In [4]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

## Set the data type

In [6]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

## 2D arrays

In [8]:
np.array([[1,2,3],[4,5,6]],dtype='float32')

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [9]:
np.array([[1,2,3],[4,5,6],[7,8,9]], dtype='float32')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

## Create a length-10 integer array filled with zeroes

In [12]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Create a 3X5 floating-point array filled with 1s

In [13]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Create a 3X3 array of uniformly distributed random values between 0 and1

In [14]:
np.random.random((3,3))

array([[0.33511134, 0.40796123, 0.53682023],
       [0.02513965, 0.17649286, 0.91355305],
       [0.66476073, 0.91872909, 0.20681723]])